export const GET_VALUTES = 'GET_VALUTES';
export const GET_VALUTES_SUCCESS = 'GET_VALUTES_SUCCESS';
export const GET_VALUTES_FAILURE = 'GET_VALUTES_FAILURE';

export const GET_SINGLE_VALUTE = 'GET_SINGLE_VALUTE';
export const GET_SINGLE_VALUTE_SUCCESS = 'GET_SINGLE_VALUTE_SUCCESS';
export const GET_SINGLE_VALUTE_FAILURE = 'GET_SINGLE_VALUTE_FAILURE';

export const GET_NEXT_PAGE = 'GET_NEXT_PAGE';
export const GET_NEXT_PAGE_SUCCESS = 'GET_NEXT_PAGE_SUCCESS';
export const GET_NEXT_PAGE_FAILURE = 'GET_NEXT_PAGE_FAILURE';

export const GET_PREVIOUS_PAGE = 'GET_PREVIOUS_PAGE';
export const GET_PREVIOUS_PAGE_SUCCESS = 'GET_PREVIOUS_PAGE_SUCCESS';
export const GET_PREVIOUS_PAGE_FAILURE = 'GET_PREVIOUS_PAGE_FAILURE';

export const SET_ID = 'SET_ID';
